export const foods =  [
    {
      id: 1,
      category: 'starter',
      title: "Paneer_tikka",
      imgSrc: 'src/assets/paneer_tikka.jpg',
      description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis, dicta!',
      price: '399 + Taxes',
    },
    {
      id: 2,
      category: 'starter',
      title: "Cookies",
      imgSrc: 'src/assets/cookies.jpg',
      description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis, dicta!',
      price: '499 + Taxes',
    },
    {
      id: 3,
      category: 'starter',
      title: "Papdi Chaat",
      imgSrc: 'src/assets/papdi_chat.jpeg',
      description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis, dicta!',
      price: '299 + Taxes',
    },
    {
      id: 4,
      category: 'soup',
      title: "Tomato Soup",
      imgSrc: 'src/assets/tomato_soup.jpeg',
      description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis, dicta!',
      price: '349 + Taxes',
    },
    {
      id: 5,
      category: 'soup',
      title: "Mix Veg Soup",
      imgSrc: 'src/assets/mix_veg_soup.jpg',
      description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis, dicta!',
      price: '349 + Taxes',
    },
    {
      id: 6,
      category: 'main_course',
      title: "Saahi Paneer",
      imgSrc: 'src/assets/sahi_paneer.jpeg',
      description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis, dicta!',
      price: '539 + Taxes',
    },
    {
      id: 7,
      category: 'main_course',
      title: "Masala Dosa",
      imgSrc: 'src/assets/masala_dosa.jpg',
      description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis, dicta!',
      price: '379 + Taxes',
    },
    {
      id: 8,
      category: 'main_course',
      title: "Paneer Biryani",
      imgSrc: 'src/assets/paneer_biryani.jpeg',
      description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis, dicta!',
      price: '449 + taxes',
    },
    {
      id: 9,
      category: 'main_course',
      title: "Smoothies",
      imgSrc: 'src/assets/smooties.jpg',
      description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis, dicta!',
      price: '319 + Taxes, Pic Any',
    },
    {
        id: 10,
        category: 'desert',
        title: "Ice Cream",
        imgSrc: 'src/assets/ice_cream.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis, dicta!',
        price: '249 + Taxes, 2 Serve',
      },
      {
        id: 11,
        category: 'desert',
        title: "Ras Malai",
        imgSrc: 'src/assets/ras_malai.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis, dicta!',
        price: '169 + Taxes, 2 Serve',
      },
      {
        id: 12,
        category: 'desert',
        title: "Gulab Jamun",
        imgSrc: 'src/assets/gulab jamun.jpeg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis, dicta!',
        price: '99 + Taxes, 2 Serve',
      },

  
  
  ]
  